apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: appcontainer
      image: tcollins520/vprofileapp:v2
      ports:
        - name: vproapp-port
          containerPort: 8080
